### ISSUE TITLE
The latest Genisys cant login to the latest Nemisys

### ISSUE THREAD

**Issue by Encritary** [iTXTech/Nemisys#3]
#### Issue description

Genisys can connect to Nemisys, but doesn't login! But with Synapse it works well.
#### OS and versions

- Nemisys: 3dc6c89
- Java: 8
- Genisys: ab35ad3
- PHP: 7.2
- Server OS: Windows Server 2012 R2 with April 2014 Update, Genisys on Ubuntu 16.04
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ZedCee** [comment]
Please properly fill out the provided template as we cannot provide adequate support without it.  I will reopen the issue once this is completed.  I have kindly re-included the template back into your issue ticket.

Also note that we do not have a version of Genisys-latest, they come with commit numbers (versions) for a reason, please provide that.  Again, once the issue is adequately filled in, I will reopen the issue for you.

**Comment by PeratX** [comment]
Of course you can't. Nemisys is using SPP v4 or v5 and Synapse is using SPP v3.

**Comment by PeratX** [comment]
I will update Genisys & Synapse after the new SPP is stable.

**Comment by Encritary** [comment]
Can you make beta build? Like in new branch

**Comment by AndreTheGamer** [comment]
Why not use Synapse? it works well. I don't think rewriting it in java will increase performance alot.
